### ISSUE TITLE
Assertion Error When Running tag_deck

### ISSUE THREAD

**Issue by AdmiralKat42** [zachalmers/Anki_Tagger#6]
I'm running into an error when running the final step of the code. To troubleshoot, I ran the code in Jupyter Notebook and ran into an error when I ran the following line:

```
# Initialize a new collection
col = Collection(os.path.join("temp_folder", anki2_file))`
```

This is the error that popped up: 

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-27-d2fab3ec1034> in <module>
      1 # Initialize a new collection
----> 2 col = Collection(path)

~\anaconda3\lib\site-packages\anki\collection.py in __init__(self, path, backend, server, log)
    106         self.server = server
    107         self.path = os.path.abspath(path)
--> 108         self.reopen()
    109 
    110         self.tr = Translations(weakref.ref(self._backend))

~\anaconda3\lib\site-packages\anki\collection.py in reopen(self, after_full_sync)
    265     def reopen(self, after_full_sync: bool = False) -> None:
    266         assert not self.db
--> 267         assert self.path.endswith(".anki2")
    268 
    269         self._last_checkpoint_at = time.time()

AssertionError:
```

Any idea what this could be a result of? The file pathway output by this line of code seems to be formatted correctly as:
`temp_folder\collection.anki21`
There just seems to be some issue with implementing this pathway with the collection function.

**Comment by zachalmers** [comment]
Not something I've encountered. Maybe it's an IO issue. Check the
permissions in the folder you're running in? Or could be an update to the
package that's causing an issue.

Z

**Comment by AdmiralKat42** [comment]
Hmm I just checked the permissions of the folder and everything is accessible. I also changed to various older versions of the anki package and the code output the same error.

**Comment by zachalmers** [comment]
Could it be an issue with --> 267 assert self.path.endswith(".anki2") given
your file name is ".anki21"

**Comment by AdmiralKat42** [comment]
I think that's got something to do with for sure. When I change .anki21 to .anki2, the code runs all the way through. 
`# The main .anki2 database file should have been extracted now
    # Look for the .anki21 file in the temp_folder
    anki2_file = [f for f in os.listdir("temp_folder") if f.endswith(".anki21")][0]
`

Although, when I do that, it doesn't successfully tag any cards:
`guid not found for card: <div>What <u>visual deficit</u> is associated with <b>pituitary adenoma</b>? </div><div><br /></div><div>{{c1::Bitemporal hemianopsia}}</div>
Tagged 0 cards. Process Complete`

**Comment by AdmiralKat42** [comment]
I have determined the source of the issue. I had some bugs with the Powershell Prompt that I was using, so I switched to the miniconda3 powershell prompt. It worked like a charm!
