### ISSUE TITLE
IO cards causing errors

### ISSUE THREAD

**Issue by jonathan-kuo11** [zachalmers/Anki_Tagger#7]
~It looks like image occlusion cards can gum up `select_cards.py` because even with increasing temperature, GPT's not going to be able to rate cards that essentially look like `"<img src=""93774cd41f7341824922497bf6d1b56e.webp"">"` or `"[#!occlusions [[rect0::113,134,123,32]]<br>[[rect0::283,244,144,31]]<br>[[rect0::119,325,172,31]]<br>[[rect0::1,446,199,30]]<br>[[rect0::480,445,161,30]] #]<br>active"`.~

~It might be helpful to have a step that removes IO cards prior to creating the embeddings, since it doesn't seem to make sense to incorporate those cards into embeddings either. This would require, I think, checking "Include notetype name" when exporting notes in plain text. It seems that there might be a few different card types floating about that are image occlusion, but I think excluding "Image Occlusion" and "IO-one by one" should catch the majority. Not sure if this will break `tag_deck.py`, though — will sub-setting only a portion of cards that can be processed and tagged mess up the merge back to Anki?~

Different error was happening, fixed. It's easy to create embeddings on junk data if you click extra buttons in "Notes in Plain Text" anki export window; make sure you ONLY have "Include unique identifier" checked and nothing else. You can throw in a `df.head()` to make sure you're embedding on the right stuff.

**Comment by zachalmers** [comment]
Totally agree. If there is broder image support with the API now would
consider tweaking to support the IO cards better. Hoping to do a round of
further development in the next month once residency things are fully
wrapped up.
